### PR TITLE
Update AppVeyor to use Cygwin

### PR DESCRIPTION
**Pull request by ararslan**
We'll see how long it takes to build. Hopefully it at least doesn't time out.

### CODE REVIEW

**Comment by ararslan** [comment]
Okay, so it can't find GCC...

**Comment by ararslan** [comment]
Any insight here, @tkelman?

**Comment by tkelman** [comment]
You can't use cygwin's gcc, you need to use the cross-compilers

**Comment by ararslan** [comment]
Okay, how do I do that then?

**Comment by tkelman** [comment]
`i686-w64-mingw32-gcc` or `x86_64-w64-mingw32-gcc`

**Comment by tkelman** [comment]
If there's any c++ or other complicated things needed, and the library builds with configure, then `--host=x86_64-w64-mingw32` will do most of the work for you

**Comment by ararslan** [comment]
Hm, still can't find a C compiler, even with `--host` 😕

**Comment by tkelman** [comment]
Doesn't look like you're passing the argument to configure at all. I'd avoid writing this as a makefile, personally.

**Comment by ararslan** [comment]
> Doesn't look like you're passing the argument to configure at all.

I'm setting `--host` as [part of `CONFIG`](https://github.com/ararslan/fftw-builder/blob/0ffdd6378a405738bb53f0d25ab8639b60b9b5d7/Makefile#L27), which is then [passed to `configure`](https://github.com/ararslan/fftw-builder/blob/0ffdd6378a405738bb53f0d25ab8639b60b9b5d7/Makefile#L47)

**Comment by tkelman** [comment]
Looks like WINNT is something that only exists in Julia's makefiles. The default make OS variable appears to expand to Windows_NT in Cygwin. But generally make will tell you things about the system you run it on, which is not necessarily the same as the system you're building for. So makefiles written like this (unless you copy over all the giant hacks Julia's makefiles do) aren't going to generalize to cross-compilation.

**Comment by ararslan** [comment]
Okay. It would be nice to get this done with Docker on Linux but I'm not even sure where to start in getting that set up. I couldn't seem to find the relevant information about how Cygwin builds their MinGW GCC in order to ensure we have something compatible in a Docker image.

In the meantime it sounds like this just straight up isn't going to work as is, so I'll close the PR.

**Comment by tkelman** [comment]
Well, this could probably be made to work, changing `ifeq ($(OS),WINNT)` to `ifeq ($(OS),Windows_NT)` would probably get a little further, and instead of adding cygwin tools by modifying PATH it would be better to run a bash command or script via a login shell. Using appveyor for building things can probably work in specific circumstances, and with a lot of work and fiddling and remote debugging.

**Comment by ararslan** [comment]
Viral had mentioned the possibility of setting up a dedicated Windows buildbot for building binaries like this, so perhaps we should just pursue that instead.

**Pull request closed without merging**
