### PR TITLE
Use Docker for Linux builds

### PR DESCRIPTION
**Pull request by ararslan**
Part of #2. Should set up a larger matrix for MinGW compilation with Docker.

### CODE REVIEW

**Comment by ararslan** [comment]
Docker command not found?!

**Comment by staticfloat** [comment]
ah, apparently you need to do this:

https://docs.travis-ci.com/user/docker/

**Comment by ararslan** [comment]
I have `sudo: required` and `services: - docker` like the docs say to do...

**Comment by staticfloat** [comment]
I think you have to be on trusty for docker?

**Comment by ararslan** [comment]
Quoth the docs:
> Travis CI automatically routes builds to run on Trusty `sudo: required` when `services: docker` is configured.

**Comment by staticfloat** [comment]
Welp that's not working, because your latest job ran on `precise`.

**Comment by ararslan** [comment]
Oh! Well dang. Worth reporting to Travis?

**Comment by ararslan** [comment]
Explicitly telling it to use Trusty seems to have done the trick.

**Comment by staticfloat** [comment]
I guess report it then.  :P

**Pull request merged**
