### PR TITLE
Use CircleCI for 32-bit Linux

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Comment by ararslan** [comment]
Well that's annoying. Things don't seem to persist across workflow jobs on CircleCI. I guess I'll combine the build and test steps.

**Comment by ararslan** [comment]
Also annoying: I can't seem to find a built-in way to attach built binaries or build artifacts to a GitHub release like you can with Travis and AppVeyor.

**Comment by ararslan** [comment]
Your knowledge of Circle has far exceeded mine, @tkelman. Do you know whether it's possible to upload the built artifacts?

**Comment by tkelman** [comment]
hadn't tried that yet. maybe check what conda-forge does, I think they use circle. or try uploading to something like bintray? or use the raw github api via curl and secure env vars

**Comment by tkelman** [comment]
> building 32-bit Linux on Circle since their VMs are actually i686.

I'm still pretty sure wherever you originally got this information from was mistaken.

**Comment by ararslan** [comment]
I contacted their support staff and the guy specifically told me that their Linux VMs were all i686.

**Comment by ararslan** [comment]
screen shot 2017-08-08 at 2 50 50 pm

**Comment by tkelman** [comment]
`uname -m` inside the vm disagrees...

**Comment by ararslan** [comment]
¯\\\_(ツ)\_/¯ Maybe they changed it at some point, who knows. All I know is what Circle told me about a year ago.

**Comment by ararslan** [comment]
```
#!/bin/bash -eo pipefail
mkdir -p ~/julia
curl -sL "${JULIA_URL}" | tar -C ~/julia -x -z --strip-components=1 -f -
~/julia/bin/julia -e 'versioninfo()'


gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Exited with code 2
```
🤔 Worked in other images and on Travis. I wonder what the deal is with the circleci/python:3 image.

Edit: HAH I think I know.

**Comment by ararslan** [comment]
Hmmmmmmmmmmmmmm
```
ERROR: LoadError: error compiling anonymous: could not load library "/home/circleci/project/build/lib/libfftw3_threads.so"
libfftw3.so.3: cannot open shared object file: No such file or directory
Stacktrace:
 [1] include_relative(::Module, ::String) at ./loading.jl:464
 [2] include(::Module, ::String) at ./sysimg.jl:14
 [3] process_options(::Base.JLOptions) at ./client.jl:315
 [4] _start() at ./client.jl:383
while loading /home/circleci/project/test.jl, in expression starting on line 27
```
I wish I didn't have to rerun the entire Travis build+test and Circle build just to put in an `ldd` for debugging...

**Comment by ararslan** [comment]
Man, no one likes the 32-bit binaries built on CI. Not on Travis, not on Circle. How sad.

**Comment by ararslan** [comment]
YASSSSS works now 🎉

**Pull request merged**
